.github/workflows/test_publish.yml, src/k8s/clients.py, src/k8s/quota.py, src/renku_crc/app.py, src/renku_crc/blueprint.py
A few issues here that @rokroskar found:
- The response from some endpoints fail because we expect to get a full quota in the response but internally in some cases the quota could also just be a string. So these cases were breaking the API. Now I have addressed this.
- Patching a resource pool was calling the method to delete the resource pool, and luckily this was failing, I have corrected this now so it should work
=> fix: adding users and showing quotas

bases/renku_data_services/data_api/server_options.py, components/renku_data_services/errors/errors.py, components/renku_data_services/storage_adapters/schemas.py, components/renku_data_services/storage_blueprints/core.py, components/renku_data_services/storage_models/core.py, components/renku_data_services/storage_schemas/api.spec.yaml, components/renku_data_services/storage_schemas/apispec.py, components/renku_data_services/storage_schemas/core.py, test/bases/renku_data_services/data_api/test_storage.py
Paths now allow everything
Validation logic for private/public is a bit more advanced now:
- Sending a private field for storage marked public results in an error
- Sending a private field for storage marked private replaces the private values with `<sensitive>`
- Changing (PATCH) storage from private to public removes the `<sensitive>` entries
All endpoints that return a cloud storage return `sensitive_fields` now
=> fix: path regex and private storage handling

.devcontainer/docker-compose.yml, .github/workflows/acceptance-tests.yml, projects/renku_data_service/Dockerfile
The defaults we had before were weird. also we were running with `--fast` which takes up way too many replicas of itself because it decides this based on the total number of cpus and when it runs on k8s it sees the total cpus on the node not the total cpus allocated to the pod.
=> fix: run sanic in single process

bases/renku_data_services/data_api/app.py, bases/renku_data_services/data_api/config.py, components/renku_data_services/crc/blueprints.py, components/renku_data_services/crc/db.py, components/renku_data_services/crc/models.py, components/renku_data_services/crc/orm.py, components/renku_data_services/git/gitlab.py, components/renku_data_services/k8s/quota.py, components/renku_data_services/users/dummy.py, poetry.lock, test/bases/renku_data_services/data_api/test_resource_pools.py, test/bases/renku_data_services/data_api/test_smoke.py, test/bases/renku_data_services/data_api/test_storage.py, test/components/renku_data_services/crc_models/hypothesis.py, test/components/renku_data_services/db/test_sqlalchemy_pool_repo.py, test/components/renku_data_services/db/test_sqlalchemy_storage_repo.py, test/components/renku_data_services/db/test_sqlalchemy_user_repo.py, test/components/renku_data_services/k8s/test_k8s_adapter.py, test/conftest.py
This fixes several instances in the code where:
- a quota can be added in the db even if it is not compatible with existing resource classes
- a class can be added if it is not compatible with an existing quota
- the quota field in the ResourcePool dataclass has be either of type Quota or None, prior to this it could also be a string that represented the name of the quota in k8s, but that complicates the code quite a bit - the Quota type contains the k8s name as its id
- fixes to the tests to work with the new changes
- changes to the tests so that the config is used when certain things that it initializes are needed - prior to this we initialized certain db adapeters or clients separately but the config type can do these even for a test scenario
/deploy
=> fix: properly validate quotas

components/renku_data_services/storage/api.spec.yaml
The storage tags were not present on every endpoint. Causing some storage endpoints to show up in the default group.
Also the python code generated for storage and the api spec did not match. Adding `"null"` as one of the options resolved this. Now the apispec and the generated code match.
=> fix(storage): make apispec up to date and add tags

.devcontainer/devcontainer.json, .dockerignore, bases/renku_data_services/data_api/config.py, components/renku_data_services/crc/api.spec.yaml, components/renku_data_services/storage/api.spec.yaml, components/renku_data_services/utils/core.py
This makes sure the merged merged API schema complies with OpenAPI spec.
closes #61 
/deploy
=> chore: prevent duplicate list entries on schema merge

components/renku_data_services/crc/db.py, test/components/renku_data_services/db/test_sqlalchemy_pool_repo.py
At the moment, on every quota update via the API, a new quota is created in k8s. This changes the logic so a quota is only updated, as expected. 
/deploy
=> fix: do not create new quota on update

components/renku_data_services/crc/db.py, components/renku_data_services/storage/db.py
See: https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#synopsis-orm.
This allows `mypy` to properly see types returned by `session.execute()` as being async, etc.
/deploy
=> chore: use async_sessionmaker

components/renku_data_services/project/blueprints.py, components/renku_data_services/project/db.py
More robust handling of the `page` and `per_page` headers in the projects blueprint.
Fixes failing schemathesis tests.
Example failing seeds:
* `--hypothesis-seed=171017779445631268920106278163870437636`
* `--hypothesis-seed=300134266653430367689664173805277011406`
=> fix: handle incorrect per_page in projects

bases/renku_data_services/keycloak_sync/config.py, components/renku_data_services/users/db.py, components/renku_data_services/users/kc_api.py
This fixes the syncing of keycloak users in the data service.
I setup iterators to do paginated requests to Keycloak and then just completely forgot to add a while loop to keep going through all possible pages. So currently only the first 20 users were imported.
I tested a job with this code on dev and it works. I use `asyncio.gather` for the user updates so if I use a nullpool then I open too many connections to postgres. That is why I added a pool with 2. I know this slows things down but this is just a job that runs periodically and it does not need to be fast. It is better for this to be slow than to nuke the db.
Once this is approved and merged. I will make a bugfix release from 0.5.0 that includes this change and then make a renku bugfix release. Currently on main in this repo we …
=> fix: keycloak user sync

.github/workflows/test_publish.yml, projects/keycloak_sync/Dockerfile, projects/renku_data_service/Dockerfile
We were missing this step for a few releases.
=> chore: add CI job to publish keycloak sync images

components/renku_data_services/namespace/orm.py, components/renku_data_services/project/orm.py
This was causing printing the namespace orm when keycloak users are synced to crash.
I did not know we can set the repr field in sqlalchemy. I will open a followup PR to set repr to false on most relationships so that things do not blow up simply by trying to print something... as they often do now.
/deploy renku-ui=ciyer/3023-namespaces
=> fix: printing of namespace outside of session

components/renku_data_services/errors/errors.py, components/renku_data_services/namespace/db.py, components/renku_data_services/project/db.py, test/bases/renku_data_services/data_api/test_groups.py
This addresses a few things:
1. Enable changing the namespace of a project
2. Fix a problem when removing a user from a group removed it from all other groups
3. Prevent removal of the owner from the group if there is no other owner
/deploy renku-ui=ciyer/3023-namespaces
=> fix: group membership and enable changing project namespace

components/renku_data_services/migrations/versions/89aa4573cfa9_cleanup_project_when_slug_is_removed.py, components/renku_data_services/namespace/db.py, components/renku_data_services/project/orm.py, test/bases/renku_data_services/data_api/test_groups.py
This was not done because the project slugs table has a foreign key pointing to projects. So the foreign key delete cascade takes care of deleting slugs when a project is deleted. But when deleting a group, this deletes the project slugs that belong to the group but the project table has no foreign key to the slugs. So for this case I added a trigger and a procedure that deletes the project when its slug is deleted.
/deploy extra-values=global.gitlab.url=https://gitlab.dev.renku.ch,global.gitlab.registry.host=registry.dev.renku.ch/
=> fix: delete project when its group is deleted

components/renku_data_services/authz/authz.py, components/renku_data_services/message_queue/converters.py, components/renku_data_services/message_queue/redis_queue.py, test/bases/renku_data_services/data_api/test_projects.py
We need to replace the role of an existing user in the authz DB when a role is patched. So when the new role is added we have to explicitly remove the old role. If not the user ends up with both roles in the authorization database. Which we do not want.
Spotted by @ciyer in testing.
Deployed over at https://github.com/SwissDataScienceCenter/renku/pull/3617
This also fixes a few other problems with the message queue:
- we were always sending a v1 header if v2 messages were being sent
- we were not emitting a project member added as owner event when a project is created
=> fix: patching existing user's project role should not add extra roles

components/renku_data_services/connected_services/api.spec.yaml
For some reason the `connected_services` api spec header was wrongly updated. This PR uses the same header as the api spec from other modules.
=> fix: update api spec header

.github/workflows/test_publish.yml, chartpress.yaml
I think for all other releases we published the image manually. I will also publish it manually for 0.12.0 which I tagged an hour ago.
=> chore: build secrets storage image with github actions

bases/renku_data_services/data_api/main.py, components/renku_data_services/base_api/blueprint.py, components/renku_data_services/connected_services/blueprints.py
WIP
Before:
```
[2024-05-24 12:53:46 +0000] [25940] [INFO] Route: renku_data_services.resource_pool_users._get_all
[2024-05-24 12:53:46 +0000] [25940] [INFO] Route: renku_data_services.resource_pool_users._get
[2024-05-24 12:53:46 +0000] [25940] [INFO] Route: renku_data_services.resource_pool_users._delete
[2024-05-24 12:53:46 +0000] [25940] [INFO] Route: renku_data_services.resource_pool_users._put
[2024-05-24 12:53:46 +0000] [25940] [INFO] Route: renku_data_services.resource_pool_users._post
```
After:
```
[2024-05-24 12:58:29 +0000] [26730] [INFO] Route: renku_data_services.resource_pool_users.get
[2024-05-24 12:58:29 +0000] [26730] [INFO] Route: renku_data_services.resource_pool_users.get_all
[2024-05-24 12:58:29 +0000] [26730] [INFO] Route: renku_data_services.resource_pool_users.put …
```
=> fix: remove the leading underscore (_) on route names

components/renku_data_services/namespace/db.py
with no order you get random results. One time when I tested, I'd get the same result on page 1 and 2.
=> fix: set order of get_namespaces query to ensure pagination works

components/renku_data_services/base_api/error_handler.py, components/renku_data_services/errors/errors.py, components/renku_data_services/user_preferences/db.py
Fixes #245.
[Sanic exceptions have a `quiet` property](https://sanic.dev/en/guide/best-practices/exceptions.html#codequietcode) which is used to suppress logging. The custom error handler is updated to use Sanic's default `log()` method and our custom error classes now also have the `quiet` attribute.
Details:
* Add `quiet` attribute to `BaseError`
* Use the default `log()` method after the `formatted_exception` has been assigned in the `default` error handler.
* Re-order exceptions to be listed by ascending HTTP status code.
* Suppress "Preferences not found for user." messages.
/deploy #notest
=> refactor: update exception logging in `CustomErrorHandler`

.github/dependabot.yml
note: multi-directory support is beta and not in the documentation other than https://github.blog/changelog/2024-04-29-dependabot-multi-directory-configuration-public-beta-now-available/
this updates poetry dependencies for all pyproject.toml's grouped together, on every sunday (when CI is unlikely to be running).
We could also have separate PRs for dev and prod dependencies.
=> chore: set up dependabot depedency updates

poetry.lock, projects/background_jobs/poetry.lock, projects/background_jobs/pyproject.toml, projects/renku_data_service/poetry.lock, projects/renku_data_service/pyproject.toml, projects/secrets_storage/poetry.lock, projects/secrets_storage/pyproject.toml, pyproject.toml
so sanic needs setuptools installed to work, they have an open PR to fix this, but for now this breaks things. But setuptools is not specified as a dependency of sanic/tracerite, so you get
```
File "/app/env/lib/python3.12/site-packages/tracerite/html.py", line 1, in <module>
import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```
Previously, the `kubernetes` library depended on `setuptools` and things just worked out that way, but the newest kubernetes library version dropped that dependency
/deploy
=> fix: add dependency on setuptools which iss an implicit dependency of sanic

bases/renku_data_services/background_jobs/config.py, bases/renku_data_services/background_jobs/core.py, bases/renku_data_services/background_jobs/main.py, components/renku_data_services/authz/authz.py, components/renku_data_services/git/gitlab.py, components/renku_data_services/migrations/alembic.ini, components/renku_data_services/namespace/blueprints.py, components/renku_data_services/namespace/db.py, components/renku_data_services/namespace/models.py, components/renku_data_services/namespace/orm.py, test/bases/renku_data_services/background_jobs/test_sync.py, test/bases/renku_data_services/data_api/conftest.py, test/bases/renku_data_services/data_api/test_groups.py, test/bases/renku_data_services/data_api/test_storage.py, test/components/renku_data_services/authz/test_authorization.py, test/components/renku_data_services/message_queue/test_queue.py
=> fix: properly cascade group permissions to all projects in the group

.devcontainer/devcontainer.json, Makefile
This is currently not being used on the main branch yet and was added in support of upcoming changes.
But it slows down the ci pipelines.
We can find a different way to set things up for the automated tests. And for developing people can still call the commands in the makefile if they want the kind setup.
=> chore(ci): do not start kind on devcontainer startup

.github/workflows/test_publish.yml
See failing job: https://github.com/SwissDataScienceCenter/renku-data-services/actions/runs/10159936043/job/28095202729#logs.
=> fix: define devcontainer image tag for git tag event

components/renku_data_services/base_models/validation.py, components/renku_data_services/connected_services/blueprints.py, components/renku_data_services/namespace/blueprints.py
also adds an extra method to allow proper validation errors in pagination returns
=> refactor: add validation to namespaces blueprint

.github/workflows/test_publish.yml
without this the action creates two tags separated by a newline which causes all kinds of trouble
=> build: fix devcontainer cache build for release CI

.gitignore, README.md, flake.lock, flake.nix, test/conftest.py
Adds a `flake.nix` file containing a development setup, building the python environment and adding some useful tools. External services can be started by a vm or a NixOS container (based on systemd-nspawn).
The test config has been slightly changed to obtain the db connection information from the environment.
=> Add a development setup using nix

components/renku_data_services/message_queue/converters.py
The group member events (adedd, updated, removed) have been wrongly translated into project member events.
=> fix: Fix messages types for group member changes

components/renku_data_services/repositories/apispec_base.py, test/bases/renku_data_services/data_api/test_repositories.py
This caused issues for internal gitlab and also when a provider wasn't set up by a user.
=> fix: empty connection id not serialized for repositories

components/renku_data_services/session/db.py
Fixes the following error:
```
data-service [2024-09-03 14:21:17 +0000] [54] [ERROR] Exception occurred while handling uri: 'https://dev.renku.ch/api/data/session_launchers/01J2E0X0M2Y3643XQ3Z9P57MBY'
data-service Traceback (most recent call last):
data-service   File "handle_request", line 102, in handle_request
data-service     try:
data-service
data-service   File "/app/env/lib/python3.12/site-packages/renku_data_services/base_api/auth.py", line 39, in decorated_function
data-service     response = await f(request, user, *args, **kwargs)
data-service                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
data-service   File "/app/env/lib/python3.12/site-packages/sanic_ext/extras/validation/decorator.py", line 75, in decorated_function
data-service     retval = await retval
data-service …
```
=> fix: patching session launcher returns 500

components/renku_data_services/message_queue/converters.py, components/renku_data_services/message_queue/models.py, components/renku_data_services/message_queue/orm.py, test/bases/renku_data_services/data_api/test_groups.py, test/bases/renku_data_services/data_api/test_projects.py, test/components/renku_data_services/message_queue/test_EventORM.py, test/components/renku_data_services/message_queue/test_queue.py
Instead of using multiple queues/streams all the events are now sent to a single stream `search.sync`. They are only intended to synchronize data between data-services and search-service.
This requires a change to the `Event.queue` field. It was used for two things: the redis qeue/stream name and the message type. Now these two are different now and so the event must carry both separately. Events are first stored to the postgres database as single value (its avro payload) and the qeue name is stored alongside. When re-creating the event object from the database, we don't have the `(header, payload)` tuple, but only a `dict[str, Any]` (the raw message). This is different to when creating the event from a `message-type` and structured avro object. Since we never need to read the structured …
=> chore: Send all search synchronisation events to a single queue

components/renku_data_services/message_queue/avro_models/io/renku/events/v2/__init__.py, components/renku_data_services/message_queue/avro_models/io/renku/events/v2/reprovisioning_finished.py, components/renku_data_services/message_queue/avro_models/io/renku/events/v2/reprovisioning_started.py, components/renku_data_services/message_queue/schemas/v2/asyncapi.yaml, components/renku_data_services/message_queue/schemas/v2/notify/events/reprovisioning_finished.avsc, components/renku_data_services/message_queue/schemas/v2/notify/events/reprovisioning_started.avsc
Ran this build step to download the current avro schema files and generate python model classes:
```
make download_avro
python components/renku_data_services/message_queue/generate_models.py
```
=> chore: Update avro models to current version

components/renku_data_services/migrations/versions/a11752a5afba_migrate_to_entity_slugs.py, components/renku_data_services/namespace/orm.py, components/renku_data_services/project/db.py, components/renku_data_services/project/orm.py
Moves the `project_slugs` table to `entity_slugs` and `project_slugs_old` to `entity_slugs_old`. This is done to prepare for more entity types to be namespaced.
/deploy renku=release-0.57.0
Note: the sequence migration has been tested:
1. Force migration revision to be `9058bf0a1a12` (before this).
2. Deploy with image tag `renku/renku-data-service:sha-345a1bb` (current `main`) and run `alembic check` and `alembic heads` to verify the DB is before this change.
3. Create some projects.
4. Re-deploy this PR and check that migration revision is `a11752a5afba` (after this).
5. Create more projects.
=> refactor: migrate to entity slugs

components/renku_data_services/app_config/config.py, components/renku_data_services/authz/authz.py, components/renku_data_services/base_models/core.py, components/renku_data_services/crc/blueprints.py, components/renku_data_services/message_queue/converters.py, components/renku_data_services/namespace/db.py, components/renku_data_services/namespace/orm.py, components/renku_data_services/project/blueprints.py, components/renku_data_services/users/blueprints.py, components/renku_data_services/users/db.py, components/renku_data_services/users/models.py, components/renku_data_services/users/orm.py, test/bases/renku_data_services/background_jobs/test_sync.py, test/bases/renku_data_services/data_api/conftest.py, test/bases/renku_data_services/data_api/test_users.py
Combines UserInfo and UserWithNamespace classes into a single user object that always has to have a namespace (as there are no users without a namespace.
=> refactor: merge UserInfo and UserWithNamespace

components/renku_data_services/project/db.py
Fixes #404.
SQL commands within a transaction should not be done concurrently.
Note that other uses of `asyncio.gather()` create one `AsyncSession` per task.
=> fix: do not use gather() in get_projects()

components/renku_data_services/migrations/versions/3cf2adf9896b_add_data_connectors.py, components/renku_data_services/namespace/orm.py
Fixes two issues with the migrations for data connectors:
1.  The migrations cannot be rolled back after creating a data connector. This was caused by leftover entries in the `entity_slugs` table.
2. The entity slug constraint was not created. The change was not picked up by Alembic; it seems Alembic can only handle `CheckConstraint` creation together with table creation, but not new constraints on an existing table, updates to them, or removing them from a table.
Manually tested:
1. Create data connectors with the deployment at `HEAD`
2. Connect to a `data-service` pod and run
```bash
/app/env/bin/python3 -m alembic -c /app/env/lib/python3.12/site-packages/renku_data_services/migrations/alembic.ini --name common downgrade 726d5d0e1f28
```
3. Check that the current revision is …
=> fix: update data connectors migrations

components/renku_data_services/base_api/error_handler.py, components/renku_data_services/errors/errors.py
=> fix: treat invalid jwt as 401

components/renku_data_services/notebooks/api/classes/image.py, test/components/renku_data_services/notebooks/test_notebooks_image_checks.py
This was causing the API to consider some images as non-existing. Whereas in reality they exist. I noticed this with this image: ghcr.io/salimkayal/renku-devcontainer-wizard:latest.
=> fix: find images when there is an oci index

.gitignore, CONTRIBUTING.md, components/renku_data_services/notebooks/api/classes/k8s_client.py, components/renku_data_services/notebooks/blueprints.py, components/renku_data_services/notebooks/core.py, components/renku_data_services/storage/api.spec.yaml, components/renku_data_services/users/models.py, test/bases/renku_data_services/data_api/conftest.py, test/bases/renku_data_services/data_api/test_notebooks.py, test/bases/renku_data_services/data_api/test_sessions.py, test/bases/renku_data_services/data_api/utils.py
This PR extracts the business logic of the JupyterServer related endpoints from the notebooks blueprints to `core.py` so that it follows other modules implementation.
Part of #303
Fixes #399
=> Notebook: refactor blueprint business logic to core

components/renku_data_services/namespace/db.py, poetry.lock, pyproject.toml
We needed one small manual cleanup to make this work.
Then we should be able to hopefully merge the dependabot update PR at #465
=> chore: update mypy to ~1.12

components/renku_data_services/app_config/config.py, test/bases/renku_data_services/data_api/conftest.py, test/bases/renku_data_services/data_api/test_connected_services.py, test/bases/renku_data_services/data_api/test_repositories.py, test/bases/renku_data_services/data_api/test_storage.py, test/conftest.py, test/utils.py
looking at other open PRs right now, running (main) tests takes around 32 minutes.
With these changes, this is down to 18 minutes.
We can further improve this by around -50% if we find a way to have the sanic client be session scoped (one sanic client per worker, not one per test). This should not cause any problems, but would require a significant refactor in how we get the function-scoped database and other `Config` properties into blueprints without rerunning the `register_all_handlers` method. Like we'd need a way to swap out the database connection of repositories per test without constructing a new sanic client. I've created #477 to further investigate this.
For reference, these are the speedups i saw on my machine for main tests with two workers, in seconds:
before memoizing yaml …
=> test: only load apispec one, don't recalculate routes on each request

components/renku_data_services/connected_services/blueprints.py, components/renku_data_services/connected_services/db.py, test/bases/renku_data_services/data_api/test_connected_services.py
Fixes #437.
1. Handle spaces for the update and delete endpoints (use `unquote()`).
2. Use `Slug.from_name()` at creation time to avoid special characters in new providers.
/deploy #notest
=> fix: handle spaces in provider_id for connected services

components/renku_data_services/project/db.py, test/bases/renku_data_services/data_api/test_projects.py
With the current Renku 2.0 UI, when a user with the "editor" role tries to update a project, e.g. the description or keywords, they are not allowed to do so because the UI sends a patch containing the current namespace.
This is fixed in this PR, the added test fails prior to the fix.
Additional note: the `if "namespace" in payload and payload["namespace"] != old_project.namespace` code line was incorrect with respect to typing but this is not caught by `mypy` because the update is passed as an untyped `dict`. I will create a new PR to deprecate and replace `db.py` updates using dictionaries as they are unsafe. The correct approach can be seen in `data_connectors` where a Patch object is used so that all update-able properties are typed.
See example:
```json
{"description":"My new …
```
=> fix: allow project editors to send patches with the current namespace

components/renku_data_services/project/db.py, test/bases/renku_data_services/data_api/test_projects.py
Follow up from #483: the issue also appears for the `visibility` field.
/deploy
=> fix: allow project editors to send patches with the current visibility

components/renku_data_services/project/blueprints.py, components/renku_data_services/project/core.py, components/renku_data_services/project/db.py, components/renku_data_services/project/models.py, test/bases/renku_data_services/data_api/test_data_connectors.py, test/bases/renku_data_services/data_api/test_projects.py
See #485.
Refactor the project update method to used a typed `ProjectPatch` instance. This means that the update code is now type-checked.
/deploy
=> refactor: use typed patch instance for project updates

bases/renku_data_services/data_api/main.py
Sentry currently detects stack traces for renku code as "system" instead of in-app. This also means it doesn't link to github source code and treats errors as 3rd party library errors.
/deploy #notest extra-values=dataService.sentry.enabled=true,dataService.sentry.dsn=https://e47c95d665684bce89984bd4595268df@sentry.dev.renku.ch/13,dataService.sentry.environment=ci-renku-3548,dataService.sentry.sampleRate=0.5
=> chore: set in app include so sentry detects our application code

components/renku_data_services/users/db.py, components/renku_data_services/users/models.py
=> refactor: use typed patch instance for user updates

bases/renku_data_services/data_api/main.py
Add GRPC integration to Sentry, which adds more information about calls to `authzed`.
Before:
After:
/deploy #notest extra-values=dataService.sentry.enabled=true,dataService.sentry.dsn=https://e47c95d665684bce89984bd4595268df@sentry.dev.renku.ch/13,dataService.sentry.environment=renku-dev-ci-ds-508,dataService.sentry.sampleRate=0.5
=> fix: add GRPC integration to Sentry

components/renku_data_services/notebooks/api/schemas/cloud_storage.py, components/renku_data_services/notebooks/blueprints.py, components/renku_data_services/notebooks/utils.py, components/renku_data_services/utils/cryptography.py
/deploy renku=feat-jupyter-free-sessions amalthea-sessions=main renku-ui=andrea/jupyter-free-build renku-gateway=master extra-values=amalthea-sessions.deployCrd=false
=> fix: add user secret key when using saved secrets

.github/workflows/acceptance-tests.yml, components/renku_data_services/notebooks/blueprints.py
If the cloud storage target dir is not absolute then we mount relative to the storage directory.
/deploy
=> fix: mount cloud storage in the storage mount dir

.github/workflows/acceptance-tests.yml, .github/workflows/test_publish.yml
this PR sets concurrency for the main tests, so old runs get properly cancelled if there's a new push.
I also changes it from `group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}` to `group: ${{ github.workflow }}-${{ github.ref || github.run_id }}`. The former is I think just copied from a stack overflow answer, but using `github.ref` makes more sense, as `github.ref` is already `refs/pull/<pr_number>/merge`, so unique per PR. `run_id` is used as a safety fallback for things that aren't PRs where we don't want concurrency.
=> chore: set up concurrency limit for tests

components/renku_data_services/notebooks/api/schemas/cloud_storage.py
Moving
https://github.com/SwissDataScienceCenter/renku-notebooks/pull/1912 from ntoebooks repo.
=> fix: consider storage config passed in when launching sessions

components/renku_data_services/notebooks/blueprints.py
Closes #528.
Add the following environment variables:
* RENKU_MOUNT_DIR    Folder which contains the container state between
hibernations
* RENKU_SESSION      Set to "1" inside a Renku user session
* RENKU_SESSION_IP   IP where the session web server should be listening
* RENKU_SESSION_PORT Port where the session web server should be listening
* RENKU_WORKING_DIR  Default current working directory of applications within the session container.
/deploy
=> fix: add Renku env variables to Renku 2.0 sessions

components/renku_data_services/notebooks/api/classes/k8s_client.py, components/renku_data_services/notebooks/config/__init__.py
If we skip the cache then when the cache fails we can take down the k8s api.
/deploy
=> fix: do not skip the k8s cache by default

components/renku_data_services/secrets/core.py
Use `default_filename` as the secret's filename for Renku 1.0 sessions.
Forgotten edit, or rebase-yanked from session secrets.
Before, if using spaces or other characters in the secret's name:
After:
/deploy
=> fix: use default_filename for secrets in Renku 1.0

bases/renku_data_services/data_api/app.py, components/renku_data_services/app_config/config.py, components/renku_data_services/notebooks/api/classes/data_service.py, components/renku_data_services/notebooks/api/schemas/cloud_storage.py, components/renku_data_services/notebooks/blueprints.py, components/renku_data_services/notebooks/config/__init__.py, components/renku_data_services/notebooks/core.py
Migrating
https://github.com/SwissDataScienceCenter/renku-notebooks/pull/1927
Depends on #566 and #565 
Also will keep this as draft and resolve/merge only when the new data connectors code and secrets that @leafty is working on is merged.
/deploy renku-ui=main renku-gateway=feat-shutdown-notebooks renku-notebooks=feat-use-different-user-labels-in-watcher
=> feat: save storage secrets 

.devcontainer/kpack/python-builder.yaml, Makefile, registries.yaml, setup-k3d-cluster.sh
This PR adds a script that allows to setup a k3d cluster in such a way that kpack and Shipwright can use it.
A k3d registry is created externally so it can be re-used if the cluster must be re-created without incurring the time required to populate it.
kpack and Shipwright can be optionally (and independently) deployed.
In the context of kpack, the image required for the builder is copied to the registry using a Kubernetes job.
=> kpack & Shipwright compatible k3d cluster setup

components/renku_data_services/app_config/config.py
there was a bug in the merging code, the notebooks spec file was saved in the `repositories` variable overwriting the repositories apispec, so this never ended up on our swagger page.
I rewrote the whole section to make is simpler and prevent this kind of error from happening again in the future.
/deploy
=> fix: merge all apispecs correctly

bases/renku_data_services/data_api/main.py, test/bases/renku_data_services/data_api/test_data_connectors.py
=> fix: make HEAD responses emtpy

components/renku_data_services/storage/rclone.py, test/bases/renku_data_services/data_api/test_storage.py
this add back s3 and other customisations for the storage schema
/deploy
=> fix: renable s3 customizations for data connectors

components/renku_data_services/authz/models.py, components/renku_data_services/authz/schemas.py, components/renku_data_services/migrations/versions/239854e7ea77_add_non_public_read_relation.py, flake.nix, test/components/renku_data_services/authz/test_authorization.py, test/components/renku_data_services/authz/test_schemas.py
=> feat: Adding new relation for listing private-only entities

components/renku_data_services/repositories/utils.py, test/bases/renku_data_services/data_api/test_repositories.py
=> fix: handle http errors when probing repositories

components/renku_data_services/notebooks/api/amalthea_patches/git_proxy.py, components/renku_data_services/notebooks/api/amalthea_patches/init_containers.py, components/renku_data_services/notebooks/blueprints.py, components/renku_data_services/notebooks/core_sessions.py
This was hardcoded for the old sessions so we just re-used the same hardcoded values from v1 sessions. But for v2 we should take this info from the environment.
closes #629 
/deploy
=> fix: use correct uid/gid when cloning git repos

.devcontainer/devcontainer.json
It seems that at some point all features from
ghcr.io/devctonainers-contrib moved to ghcr.io/devcontainers-extra. That is why the newest version of poetry was not installed. Because the old path still has all the stuff but no updates.
=> chore: update devcontainer features path

components/renku_data_services/migrations/versions/75c83dd9d619_migrate_copied_custom_environments_to_.py, test/bases/renku_data_services/data_api/test_migrations.py
There is a bug where environments were not copied when a project was copied. So the environment was shared between the original project and the copied project. This migration makes new environments (copied from the original project) for all copied projects.
/deploy
=> fix: migrate environments from copied projects

components/renku_data_services/app_config/config.py, components/renku_data_services/session/k8s_client.py
PR Stack:
* #625
* (this) #647
* #648
* #657
* #656
Related PRs:
* https://github.com/SwissDataScienceCenter/renku-notebooks/pull/2007
* https://github.com/SwissDataScienceCenter/renku/pull/3878
/deploy #notest renku=build/session-env-builders renku-ui=leafty/session-env-builders-5 renku-notebooks=leafty/shipwright-buildrun-cache extra-values=dataService.imageBuilders.enabled=true,dataService.imageBuilders.outputImagePrefix=harbor.dev.renku.ch/flora-dev/,dataService.imageBuilders.pushSecretName=flora-docker-secret
=> refactor: use the k8s cache for buildruns

components/renku_data_services/app_config/config.py, components/renku_data_services/session/constants.py, components/renku_data_services/session/crs.py, components/renku_data_services/session/db.py, components/renku_data_services/session/k8s_client.py, components/renku_data_services/session/models.py
PR Stack:
* #625
* #647
* #648
* (this) #657
* #656
Support defining retention parameters for build runs.
Related PR: https://github.com/SwissDataScienceCenter/renku/pull/3913
/deploy #notest renku=leafty/define-buildrun-retention renku-ui=leafty/session-env-builders-5 renku-notebooks=leafty/shipwright-buildrun-cache extra-values=dataService.imageBuilders.enabled=true,dataService.imageBuilders.pushSecretName=flora-docker-secret,dataService.imageBuilders.buildRunRetentionAfterFailedSeconds=86400,dataService.imageBuilders.outputImagePrefix=harbor.dev.renku.ch/flora-dev/
=> feat: define retention parameters

components/renku_data_services/app_config/config.py, components/renku_data_services/session/constants.py, components/renku_data_services/session/db.py, components/renku_data_services/session/k8s_client.py, components/renku_data_services/session/models.py
/deploy #notest renku=build-timeouts renku-notebooks=leafty/shipwright-buildrun-cache renku-ui=build/session-env-builders extra-values=dataService.imageBuilders.enabled=true,dataService.imageBuilders.pushSecretName=ralf-docker-secret,dataService.imageBuilders.buildRunRetentionAfterFailedSeconds=86400,dataService.imageBuilders.buildRunTimeoutSeconds=10,dataService.imageBuilders.outputImagePrefix=harbor.dev.renku.ch/ralf-dev/
tested in the deployment, builds fail after 10 seconds with
```
- lastTransitionTime: '2025-02-28T08:49:16Z'
message: BuildRun renku-01jn5vxf3kn6qs8w52h32d57yn failed to finish within 10s
reason: BuildRunTimeout
status: 'False'
type: Succeeded
```
=> feat: allow configuring buildrun build timeout

components/renku_data_services/app_config/config.py, components/renku_data_services/session/crs.py, components/renku_data_services/session/db.py, components/renku_data_services/session/k8s_client.py, components/renku_data_services/session/models.py
Add support for configuring node selector and tolerations for container image builds.
The node selector and tolerations are added to the Shipwright BuildRun object which in turn are added to the Pod running the image build.
Related PR: https://github.com/SwissDataScienceCenter/renku/pull/3920
Note: as tests are not running against k8s for now, there is no test added for this PR.
The values in the deploy string below correspond to:
```yaml
nodeSelector:
renku.io/node-purpose: image-build
tolerations:
- effect: NoSchedule
key: renku.io/dedicated
operator: Equal
value: image-build
```
/deploy #notest renku=leafty/node-selection renku-notebooks=leafty/shipwright-buildrun-cache renku-ui=build/session-env-builders extra-values=dataService.imageBuilders.enabled=true,dataService.imageBuilders.push …
=> feat: select specific nodes for image builds

bases/renku_data_services/background_jobs/config.py, components/renku_data_services/app_config/config.py, components/renku_data_services/namespace/db.py, components/renku_data_services/project/db.py, components/renku_data_services/search/core.py, components/renku_data_services/search/db.py, components/renku_data_services/search/decorators.py, components/renku_data_services/search/models.py, components/renku_data_services/users/db.py, flake.nix, test/bases/renku_data_services/background_jobs/test_sync.py, test/bases/renku_data_services/data_api/test_groups.py, test/bases/renku_data_services/data_api/test_migrations.py, test/bases/renku_data_services/data_api/test_projects.py, test/components/renku_data_services/search/test_db.py
- Add a decorator that intercepts db calls to additionally update the search staging table
/deploy renku=build/search-migration-part1
=> feat: sync entity changes to the solr staging table

bases/renku_data_services/data_api/app.py, components/renku_data_services/app_config/config.py, components/renku_data_services/session/blueprints.py, components/renku_data_services/session/core.py
Configure `renku-data-services` for session image builds based on the helm chart values.
* If `IMAGE_BUILDERS_ENABLED is True` then the new session environments and image builds are available.
* If `IMAGE_BUILDERS_ENABLED is False` then users do not have access to he new session environments and image builds.
* The API will not validate `POST` or `PATCH` requests which configure image builds.
* The API will not answer calls to the `/builds` endpoints.
Deployments:
* Feature enabled -> https://renku-ci-ui-3511.dev.renku.ch/
* Feature disabled -> https://renku-ci-ui-3538.dev.renku.ch/
=> feat: use the feature gate for image builds

components/renku_data_services/session/db.py, components/renku_data_services/session/k8s_client.py, components/renku_data_services/session/models.py
Closes #671.
Example BuildRun metadata created with this change:
```yaml
apiVersion: shipwright.io/v1beta1
kind: BuildRun
metadata:
annotations:
renku.io/build_id: 01JNJPPZMWRYY0M61Z71VYW5SV
renku.io/environment_id: 01JNJP4YSFBSX8YXQDQQ84F9XE
renku.io/launcher_id: 01JNJP4YVB8C57TMMDPBCD4QHD
renku.io/project_id: 01JNJP4HR642H8PPGGD3RWZG9H
creationTimestamp: "2025-03-05T08:28:18Z"
generation: 1
labels:
renku.io/safe-username: 89a00f6e-8ada-43f8-92aa-6d28a40ba786
name: renku-01jnjppzmwryy0m61z71vyw5sv
namespace: renku-ci-ds-704
resourceVersion: "455312834"
uid: de8a6adf-b96e-4fbf-851e-97b3d3cfaa59
```
/deploy #notest renku=build/session-env-builders renku-notebooks=leafty/shipwright-buildrun-cache renku-ui=leafty/session-env-builders-9 …
=> feat: add annotations to buildruns

components/renku_data_services/notebooks/api/amalthea_patches/init_containers.py
Fixes a forgotten change in #643.
After this is merged, deployments need to specify `renku-notebooks=master` to use a compatible version of `git-clone`.
=> fix: remove GIT_CLONE_WORKSPACE_MOUNT_PATH from manifests

components/renku_data_services/authz/schemas.py, components/renku_data_services/migrations/versions/483af0d70cf4_migrate_authz_schema_to_v6.py, test/components/renku_data_services/authz/test_schemas.py
NOTE: This is targeting a build / feature branch.
This adds the initial changes for the authorization schema required for the project disentanglement pitch.
Below is a diff of the old and new schemas. I did not want to rename any relations for now. I will do this towards the end of the build in a separate PR.
=> feat: authz schema changes for data connectors

components/renku_data_services/project/core.py, test/bases/renku_data_services/data_api/test_projects.py
See: #712.
What is done with this change:
* Validate the repository URL (when the project is created or updated): the repository URL must be an HTTP or HTTPS URL. SSH is not supported by RenkuLab at the moment.
* Remove exact duplicates.
What is not included with this change:
* Resolve the user-provided URL to a canonical URL (e.g. https://github.com/SwissDataScienceCenter/renku-data-services -> https://github.com/SwissDataScienceCenter/renku-data-services.git). This would require connecting validation code with connected services and is left for a future change.
/deploy #notest renku=release-0.66.0
=> fix: validate git URLs

components/renku_data_services/notebooks/api/classes/k8s_client.py, components/renku_data_services/notebooks/config/__init__.py, components/renku_data_services/notebooks/core.py, test/bases/renku_data_services/data_api/test_notebooks.py
* Using the DummyK8sClient we don't need an actual K8s cluster to check our api calls end up where expected.
* Implemented the strict minimum to pass the current tests
* Everything else raises an exception.
* Removed code in the test
* Fixed warnings
* Fixed missing call to `super().__init__()`
* Removed unused fixtures
* Removed dependency on `ClusterRequired`
=> fix: Kubernetes client tests

.devcontainer/devcontainer.json
The feature was failing because a newer release of k9s has mishapen or different formatting for releases on github. And when this feature tries to install from the github releases it fails.
=> chore: pin k9s cli version

components/renku_data_services/base_api/error_handler.py, test/conftest.py
This PR aims to force the temporary database names to start with a letter rather than a number. Please suggest a more reasonable solution if the solution here isn't acceptable.
The reason behind this change is the following: most Postgres clients use a syntax like the following for interacting with databases:
```
DROP DATABASE 01jqedjvej25v1c50jfba9m7w1_master
```
Any database name starting with a number is interpreted as the beginning of a numeric literal _in Postgres_ (citation needed) and requires proper escaping. Sadly, in all the clients I tried, that doesn't happen and I get some variation of the following error when trying to drop temporary DBs
> ERROR:  trailing junk after numeric literal at or near "01jqedjvej25v1c50jfba9m7w1_master"
LINE 1: drop database …
=> test: force temporary db name to start with a letter

bases/renku_data_services/data_api/app.py, bases/renku_data_services/data_api/main.py, components/renku_data_services/app_config/config.py, components/renku_data_services/search/blueprints.py, components/renku_data_services/search/core.py, components/renku_data_services/search/reprovision.py, flake.nix
If a solr migration requires a reindex, a background task is started on startup that reprovisions the search index.
/deploy
=> fix: Start reprovisioning search index if a migration requires it

components/renku_data_services/search/core.py, components/renku_data_services/search/db.py, components/renku_data_services/solr/solr_client.py, flake.nix, test/components/renku_data_services/search/test_core.py
Fixes updates of search entries to always overwrite existing documents.
/deploy
=> fix: Updating search documents without optimistic concurrency control

components/renku_data_services/notebooks/blueprints.py, components/renku_data_services/notebooks/core_sessions.py
This adresses an issue reported by a user on discourse. Since we were updating the limits only on start - but not when patching, the session can fail to resume if you switch the resource class with one with a larger memory. This is because the patching was not updating the memory limit and the request would be > the limit after patching.
/deploy
=> fix: apply memory limits when patching

components/renku_data_services/k8s/clients.py, components/renku_data_services/k8s/models.py, components/renku_data_services/k8s_watcher/db.py
Avoid one or more call to `lower()` on each K8s API call.
We cannot rely on just using `kind`, as the K8s API sometimes returns it in lower case and sometimes requires the exact case to be used.
Instead, we use `singular` which is set and initiaized as `kind` in lower case, thus calling `lower()` only on instantation of objects.
Also switch from a list of kinds to cache to a set.
=> fix: improve efficiency of the K8s Entity Cache

components/renku_data_services/search/user_query_parser.py, test/components/renku_data_services/search/test_user_query_parser.py
No input should make the query parser fail, but fallback to a text search.
/deploy renku=release-0.69.0
=> fix: Fix query parser for random input

components/renku_data_services/migrations/versions/f4ad62b7b323_cleanup_data_connector_when_slug_is_.py
Closes #859.
The migration adds a trigger and deletes the straggler data connectors which should have been deleted previously.
Manual tests:
1. On this deployment:
1. Create a group
2. Create a data connector in the group
3. Delete the group
4. Check that listing all data connectors does not crash data services (HTTP 500)
2. On https://ci-renku-4017.dev.renku.ch/v2:
1. Deploy before this change
2. Create a group
3. Create a data connector in the group
4. Delete the group
5. Listing all data connectors will crash data services (HTTP 500)
6. Upgrade to this version
7. Check that listing all data connectors does not crash data services (HTTP 500)
/deploy
=> fix: delete data connector when its slug is deleted

.devcontainer/devcontainer.json, flake.nix, projects/renku_data_service/Dockerfile
Related PR: https://github.com/SwissDataScienceCenter/csi-rclone/pull/58
/deploy extra-values=global.csi-rclone.install=true,notebooks.cloudstorage.enabled=true,notebooks.cloudstorage.storageClass=csi-rclone-doi-zenodo,csi-rclone.storageClassName=csi-rclone-doi-zenodo,global.rcloneStorageClass=csi-rclone-doi-zenodo,amalthea-sessions.rcloneStorageClass=csi-rclone-doi-zenodo-secret-annotation,csi-rclone.csiNodepluginRclone.tolerations[0].key=renku.io/dedicated,csi-rclone.csiNodepluginRclone.tolerations[0].operator=Equal,csi-rclone.csiNodepluginRclone.tolerations[0].value=user,csi-rclone.csiNodepluginRclone.tolerations[0].effect=NoSchedule,csi-rclone.csiNodepluginRclone.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key=renku.io/n …
=> feat: update to rclone v1.69.2+renku-1

bases/renku_data_services/data_api/config.py, bases/renku_data_services/data_api/main.py, bases/renku_data_services/secrets_storage_api/config.py, bases/renku_data_services/secrets_storage_api/main.py, components/renku_data_services/app_config/logging.py, test/components/renku_data_services/app_config/test_logging.py
Removes the `LoggerAdapter` that could be used to wrap existing loggers and instead uses a `ContextVar` to track the request_id in a context sensitiv way. It is set from within a sanic on_request handler and retrieved right before the log record is emitted.
/deploy
=> Automatically log request_id obtained from sanic

components/renku_data_services/users/kc_api.py, poetry.lock, projects/renku_data_service/poetry.lock, projects/renku_data_tasks/poetry.lock, projects/secrets_storage/poetry.lock
In 0.70.1 in the data tasks we see the following errors:
```
data-tasks Traceback (most recent call last):                                                                                                data-tasks   File "/app/env/lib/python3.13/site-packages/renku_data_services/data_tasks/taskman.py", line 181, in __wrap_task
data-tasks     await tf()
data-tasks   File "/app/env/lib/python3.13/site-packages/renku_data_services/data_tasks/task_defs.py", line 390, in sync_admins_from_keycloakdata-tasks     await admin_sync.sync_admins_from_keycloak(dm.kc_api, dm.authz)
data-tasks   File "/app/env/lib/python3.13/site-packages/renku_data_services/authz/admin_sync.py", line 9, in sync_admins_from_keycloak
data-tasks     kc_admin_user_ids = [payload["id"] for payload in …
```
=> fix: expired keycloak tokens in tasks

bases/renku_data_services/data_api/main.py, components/renku_data_services/base_models/core.py, components/renku_data_services/data_connectors/db.py, components/renku_data_services/search/blueprints.py, components/renku_data_services/search/reprovision.py, components/renku_data_services/solr/solr_client.py, test/bases/renku_data_services/data_api/conftest.py, test/components/renku_data_services/search/test_reprovision.py
For reprovisioning it is necessary to get all entities. When selecting data connectors from the db, there was always a call to authz to first get all identifiers of resources the requesting user has read access to. For internal service admins, this doesn't work, because they are not modelled in authz. For admins in general the call should be prevented, because admins can see everything. 
This change skips the authz call if the requesting user is an admin. Additionally the search reprovisioning code uses an internal service admin for doing its work and not the user passed through from the endpoint call. 
/deploy
=> fix: Skip authz if admin is requesting data connectors

components/renku_data_services/project/db.py
The implementation has several issues that make it very slow:
- It doesn't implement any paging, so we are potentially transporting
a lot of data. This is not fixed in this PR.
- At very first, it retrieves *all* copied projects for a given
template_id and then filters it in memory to retain only the
accessible ones of the current user.
This is done by next retrieving all project ids the user has access
to, including all public ones. This is potentially returning a lot
of data.
The filtering then continues to loop through the database objects
and checks each id for membership in the `project_ids` list. A
python list has O(n) time for membership tests, so depending on the
number of results this gets slow quite quickly.
Measuring this call shows that by far the longest time is spent …
=> fix: refactor get_all_project_copies for performance reasons

Makefile
Also normalise to tabs alignements within the `*CODEGEN` variables, this is a single character on the command line instead of 4 when executing the command. This counts towards the maximum size of the arguments string the SHELL supports.
=> chore: Factorise common CODEGEN arguments

components/renku_data_services/notebooks/core_sessions.py
Closes #899.
Adds:
* RENKU_SECRETS_PATH -> folder where user secrets are mounted
* RENKU_PROJECT_ID -> the project ID
* RENKU_PROJECT_PATH -> the full project path (namespace + slug)
* RENKU_LAUNCHER_ID -> the launcher ID
/deploy
=> feat: add  new env vars in sessions

.github/CODEOWNERS
This allows their reviews on PRs to protected branches to count.
I cannot add them to the python maintainers group because then I will have to add them to the SDSC org fully. And I think that causes other permissions to be assigned to them - i.e. like k8s access.
=> chore: add Salim and Samuel to codeowners

bases/renku_data_services/data_api/app.py, bases/renku_data_services/data_api/dependencies.py, components/renku_data_services/connected_services/api.spec.yaml, components/renku_data_services/connected_services/db.py, components/renku_data_services/connected_services/dummy_async_oauth2_client.py, components/renku_data_services/connected_services/provider_adapters.py, components/renku_data_services/connected_services/utils.py, components/renku_data_services/notebooks/api/classes/data_service.py, components/renku_data_services/notebooks/api/classes/server.py, components/renku_data_services/notebooks/blueprints.py, components/renku_data_services/notebooks/config/__init__.py, components/renku_data_services/notebooks/core.py, components/renku_data_services/notebooks/core_sessions.py, components/renku_data_services/notebooks/image_check.py, components/renku_data_services/repositories/db.py, flake.nix, test/bases/renku_data_services/data_api/test_connected_services.py, test/utils.py
Also add some logging if things go wrong.
This adds a quick fix to allow private images from GitHub container registry. Unfortunately, GitHub doesn't allow access via tokens generated by "GitHub App". See details [here](https://github.com/orgs/community/discussions/24636) and the corresponding [open issue](https://github.com/github/roadmap/issues/558). Luckily it does work using a "GitHub OAuth App". The solution will be to add two integrations for GitHub - one is the GitHub App we are already using for accessing repositories. Then there is one GitHub OAuth App for accessing (private) images. In order to make this work, the user must still connect at github - so in case an integration is added with the ghcr.io domain, we must configure the provider adapter to connect to github.com for …
=> Check for image_registry_url when getting GH installations
