.devcontainer/devcontainer.json, components/renku_data_services/crc_migrations/versions/0044b54a89b9_migrate_old_crc_tables.py, components/renku_data_services/storage_schemas/api.spec.yaml
=> feat: add old crc migration and fix openapi schema

components/renku_data_services/crc_migrations/versions/5403953f654f_fix_primary_key_sequences.py
=> fix: migrate primary key resource_pool sequences

.devcontainer/devcontainer.json, components/renku_data_services/crc/blueprints.py, components/renku_data_services/crc_migrations/versions/5403953f654f_fix_primary_key_sequences.py, test/bases/renku_data_services/data_api/test_resource_pools.py
=> fix(crc): listing users

bases/renku_data_services/data_api/config.py, components/renku_data_services/utils/core.py
@rokroskar I think you can just merge this into #77
=> code suggestions

Makefile, bases/renku_data_services/data_api/app.py, bases/renku_data_services/data_api/main.py, components/renku_data_services/config/__init__.py, components/renku_data_services/config/config.py, components/renku_data_services/crc/db.py, components/renku_data_services/migrations/env.py, components/renku_data_services/storage/db.py, components/renku_data_services/user_preferences/db.py, projects/renku_data_service/pyproject.toml, pyproject.toml, test/bases/renku_data_services/data_api/test_resource_pools.py, test/bases/renku_data_services/data_api/test_smoke.py, test/bases/renku_data_services/data_api/test_storage.py, test/bases/renku_data_services/data_api/test_user_preferences.py, test/components/renku_data_services/data_api/test_config.py, test/components/renku_data_services/db/test_sqlalchemy_pool_repo.py, test/components/renku_data_services/db/test_sqlalchemy_storage_repo.py, test/components/renku_data_services/db/test_sqlalchemy_user_preferences_repo.py, test/components/renku_data_services/db/test_sqlalchemy_user_repo.py, test/components/renku_data_services/users/test_gitlab.py, test/conftest.py
=> sync origin/main

.github/workflows/test_publish.yml, components/renku_data_services/crc/blueprints.py, components/renku_data_services/user_preferences/blueprints.py
This should hopefully make the tests properly fail.
=> chore: run style checks in a separate job

Makefile
using git subtrees doens't work out, it gets confused after squash merging a PR. So this just switches it to downloading the repo directly
=> chore: fix dowloading of avro schemas

components/renku_data_services/migrations/utils.py
this code tried to lock a table before the table exists, which fails the migration.
=> fix migration

test/bases/renku_data_services/data_api/conftest.py, test/bases/renku_data_services/data_api/test_groups.py, test/bases/renku_data_services/data_api/test_namespaces.py, test/bases/renku_data_services/data_api/test_projects.py, test/bases/renku_data_services/data_api/test_sessions.py
=> move sanic client to common fixture

components/renku_data_services/message_queue/avro_models/io/renku/events/v1/project_created.py, components/renku_data_services/message_queue/avro_models/io/renku/events/v1/project_updated.py, components/renku_data_services/message_queue/redis_queue.py, components/renku_data_services/message_queue/schemas/project/v1/events/created.avsc, components/renku_data_services/message_queue/schemas/project/v1/events/updated.avsc, components/renku_data_services/project/db.py
=> fix: add missing await when creating events

components/renku_data_services/crc/api.spec.yaml, components/renku_data_services/namespace/api.spec.yaml, components/renku_data_services/project/api.spec.yaml, components/renku_data_services/secrets/api.spec.yaml, components/renku_data_services/session/api.spec.yaml, components/renku_data_services/storage/api.spec.yaml, components/renku_data_services/user_preferences/api.spec.yaml, components/renku_data_services/users/api.spec.yaml
The secrets api spec is not merged with the others so its spec description was not changed.
=> chore: make apispec description and version uniform

components/renku_data_services/project/db.py
Minor fix. Thanks for spotting this Ralf.
=> fix: add missing awaits when checking permissions for projects

bases/renku_data_services/data_api/main.py
/deploy extra-values=dataService.sentry.enabled=true,dataService.sentry.dsn=https://e47c95d665684bce89984bd4595268df@sentry.dev.renku.ch/13,dataService.sentry.environment=ci-renku-3548,dataService.sentry.sampleRate=0.5
=> fix: quote sentry types

test/bases/renku_data_services/data_api/test_schemathesis.py
closes #231 
this collects execution times using a session scoped fixture and then checks that 95% of them took no longer than 100ms to complete (in absolute terms, around 15 of our 269 tests can be slower than this.)
=> test: make schemathesis request time checks more consistent

projects/background_jobs/Dockerfile, projects/renku_data_service/Dockerfile, projects/secrets_storage/Dockerfile
=> fix: make docker builds deterministic

components/renku_data_services/storage/rclone.py
=> fix: obscure rclone config before testing connections

components/renku_data_services/base_api/error_handler.py, components/renku_data_services/base_api/misc.py, components/renku_data_services/migrations/alembic.ini, components/renku_data_services/migrations/env.py, components/renku_data_services/migrations/utils.py, components/renku_data_services/users/blueprints.py, test/bases/renku_data_services/data_api/test_schemathesis.py
=> fix: query args validation of /user/secrets GET

.devcontainer/devcontainer.json, components/renku_data_services/data_connectors/core.py, test/bases/renku_data_services/data_api/test_data_connectors.py
Fixes deleting storage configuration fields by setting them to `null`.
=> fix: delete storage config fields

.github/workflows/test_publish.yml
=> ci: make avro schema check optional

components/renku_data_services/crc/models.py, test/components/renku_data_services/db/test_sqlalchemy_pool_repo.py
This was causing tests to fail sporadically. Closes #432.
=> chore: correct resource pool comparison in tests

components/renku_data_services/namespace/db.py, test/bases/renku_data_services/data_api/test_namespaces.py
=> fix: correct pagination for namespaces

components/renku_data_services/platform/blueprints.py, components/renku_data_services/platform/core.py, components/renku_data_services/platform/db.py, components/renku_data_services/platform/models.py
=> refactor: use typed patch instance for platform config updates

components/renku_data_services/message_queue/db.py, components/renku_data_services/migrations/versions/584598f3b769_expand_and_separate_environments_from_.py, components/renku_data_services/notebooks/api/classes/k8s_client.py, components/renku_data_services/notebooks/blueprints.py, test/bases/renku_data_services/data_api/test_notebooks.py
/deploy renku=feat-jupyter-free-sessions amalthea-sessions=main renku-ui=andrea/jupyter-free-build extra-values=amalthea-sessions.deployCrd=false #notest
=> fix: failing tests and other issues

Makefile
* ignore return value in case of meaningful changes
* hide comments from the make output
=> chore: fix make schemas

components/renku_data_services/notebooks/api/classes/k8s_client.py
See the 2 commits for further details
=> fix: 2 small kr8s issues

components/renku_data_services/notebooks/core.py
Migrating
https://github.com/SwissDataScienceCenter/renku-notebooks/pull/1901
=> fix: remove unused field from secrets storage request

components/renku_data_services/notebooks/api/amalthea_patches/general.py
Migrating
https://github.com/SwissDataScienceCenter/renku-notebooks/pull/1984
/deploy
=> fix: Mount /dev/shm to the correct container

bases/renku_data_services/data_api/app.py, components/renku_data_services/data_connectors/db.py, components/renku_data_services/project/blueprints.py, components/renku_data_services/project/core.py, test/bases/renku_data_services/data_api/test_projects.py
Changes error message when cannot copy project's data connectors.
=> chore: change copy project error message

components/renku_data_services/namespace/blueprints.py, test/bases/renku_data_services/data_api/test_groups.py
=> fix: validate group member to be removed

components/renku_data_services/notebooks/api/classes/k8s_client.py, test/components/renku_data_services/k8s/test_k8s_adapter.py
Migrating
https://github.com/SwissDataScienceCenter/renku-notebooks/pull/1923
/deploy
=> fix: patching wrong environment variables when resuming

bases/renku_data_services/data_api/app.py, components/renku_data_services/notebooks/blueprints.py, components/renku_data_services/notebooks/utils.py
closes #586 
I remember there were also calls to storage service but those seem to have been migrated already
/deploy
=> fix: do not call dataservice through network from itself

DEVELOPING.md, flake.lock, flake.nix
Remove poetry2nix, because it is not maintained and incompatible with poetry 2.
=> Update nix dev setup

projects/background_jobs/Dockerfile, projects/renku_data_service/Dockerfile, projects/secrets_storage/Dockerfile
The code screening keeps complaining about this. It is not really a bug or anything like that.
=> chore: fix AS keyword to uppercase in dockerfiles

components/renku_data_services/session/db.py, test/bases/renku_data_services/data_api/test_projects.py
=> fix: create new custom environment when copying project

components/renku_data_services/authz/models.py, components/renku_data_services/authz/schemas.py, components/renku_data_services/migrations/versions/239854e7ea77_add_non_public_read_relation.py, flake.nix, test/components/renku_data_services/authz/test_authorization.py, test/components/renku_data_services/authz/test_schemas.py
Reopen for merging it into the main branch. Original PR is #611
=> Private resource permission

components/renku_data_services/app_config/config.py, components/renku_data_services/search/__init__.py
/deploy renku=build/search-migration-part1
=> fix: swagger page search reprovisioning

.github/workflows/acceptance-tests.yml
* Run the Cypress acceptance tests for v2
* Bump the Renku action to 1.14.1
* Add job names and adjust a few details
/deploy
=> ci: update acceptance tests action

components/renku_data_services/notebooks/blueprints.py
=> fix: set memory limits on v2 sessions

.github/workflows/acceptance-tests.yml
=> chore: bump renku-action to 1.16.0

.github/workflows/acceptance-tests.yml
V2 tests were not running correctly. This fixes it
/deploy renku=release-0.66.0
=> ci: add cypress acceptance tests folder

bases/renku_data_services/data_api/main.py, components/renku_data_services/app_config/config.py, components/renku_data_services/solr/solr_client.py, components/renku_data_services/solr/solr_migrate.py, test/components/renku_data_services/solr/test_solr_client.py, test/components/renku_data_services/solr/test_solr_migrate.py, test/conftest.py
- Allows to create and get the status of a solr core
/deploy
=> fix: Ensure an existing solr core

components/renku_data_services/notebooks/api/classes/k8s_client.py, components/renku_data_services/notebooks/api/classes/server.py, components/renku_data_services/notebooks/blueprints.py, components/renku_data_services/notebooks/config/__init__.py, components/renku_data_services/notebooks/core.py, components/renku_data_services/notebooks/core_sessions.py, test/bases/renku_data_services/data_api/test_notebooks.py, test/bases/renku_data_services/data_api/test_sessions.py
A series of cleanups. It should be easier to review and validate these commits by commits than as a lump package as they are each focused on a single rename / topic.
=> Build external resources cleanups bis

bases/renku_data_services/k8s_cache/main.py
=> chore: ignore pybandit warning

components/renku_data_services/k8s/clients.py, components/renku_data_services/k8s_watcher/core.py, components/renku_data_services/notebooks/crs.py
=> fix: fix session synchronization issues

components/renku_data_services/notebooks/core_sessions.py
Closes #820.
Demo:
* https://renku-ci-ds-821.dev.renku.ch/v2/projects/flora.thiebaut/flora-test
/deploy renku=release-0.68.0
=> fix: resolve clashing mount points issue with data connectors

components/renku_data_services/k8s/clients.py, components/renku_data_services/k8s_watcher/core.py, components/renku_data_services/notebooks/core_sessions.py, components/renku_data_services/notebooks/crs.py
/deploy renku=release-0.68.0 amalthea-sessions=fix-tolerations-update
=> fix: properly update resource class when patching session

bases/renku_data_services/data_api/app.py, components/renku_data_services/search/blueprints.py
/deploy #notest renku=data-svc-posthog renku-gateway=login-metrics extra-values=posthog.enabled=true,posthog.apiKey=phc_9KXbWU5fPFWJeBQa6n53deAJJKfjqedLJHhMohutDS1,posthog.host=https://eu.i.posthog.com,posthog.environment=development
=> feat: add metrics for search

components/renku_data_services/search/solr_token.py, test/bases/renku_data_services/data_api/conftest.py, test/bases/renku_data_services/data_api/test_search.py
Starting out with two simple cases to test search order.
/deploy renku=release-0.69.0
=> fix: Add two simple search tests and fix type:dataconnector search query

components/renku_data_services/notebooks/core_sessions.py
This was a function (ie a getter) that was treated as if it had @property.
closes #846
=> fix: creation of image pull secrets

.github/workflows/test_publish.yml
=> chore: Try parallel publishing on ci

DEVELOPING.md
https://github.com/SwissDataScienceCenter/renku-data-services/wiki/Coding-guidelines
=> chore: add coding guidelines

bases/renku_data_services/background_jobs/config.py, bases/renku_data_services/background_jobs/core.py, bases/renku_data_services/background_jobs/dependencies.py, bases/renku_data_services/background_jobs/main.py, bases/renku_data_services/data_api/dependencies.py, bases/renku_data_services/k8s_cache/config.py, bases/renku_data_services/k8s_cache/dependencies.py, bases/renku_data_services/k8s_cache/main.py, bases/renku_data_services/secrets_storage_api/dependencies.py, components/renku_data_services/app_config/config.py, test/bases/renku_data_services/background_jobs/test_sync.py
=> refactor: change background jobs and k8s watcher to new dependency management pattern

components/renku_data_services/notebooks/blueprints.py, components/renku_data_services/notebooks/core_sessions.py
=> fix: delete anonymous sessions right after pausing

components/renku_data_services/migrations/versions/8413f10ef77f_modify_stored_procedures.py, test/bases/renku_data_services/data_api/test_migrations.py, test/bases/renku_data_services/data_api/test_namespaces.py
closes #927 
This only happens when data connectors owned by projects were removed. 
/deploy
=> fix: do not delete project when dc is deleted

components/renku_data_services/notebooks/core_sessions.py
=> fix: remove print() in core_sessions.py

.github/workflows/test_publish.yml, components/renku_data_services/notebooks/core_sessions.py, components/renku_data_services/notebooks/image_check.py
- catch another auth error when checking image access
- add all secrets to the session, internal gitlab and connected services
/deploy
=> fix: Fix some issues with private images

components/renku_data_services/session/k8s_client.py
=> fix: correct handling of build run condition

components/renku_data_services/notebooks/utils.py, test/components/renku_data_services/notebooks/test_notebooks_utils.py
=> fix: correct node affinity intersection
